name: sehatmand_pakistan
description: SehatMandPakistan - Your AI Health Companion
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.0

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0

  # Icons
  flutter_svg: ^2.0.9

  # Utils
  intl: ^0.19.0
  uuid: ^4.2.2

  # HTTP
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1

  # Maps & Location
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.4
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true